version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql_container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: genie
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mongo:
    image: mongo:6
    container_name: mongo3-container
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: ./backend
    container_name: springboot_app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - mongo

  frontend:
    build:
      context: ./frontend
    container_name: react_app
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mysql_data:
  mongodb_data:
