global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'mysql_container'
    static_configs:
      - targets: ['mysql_container:3306']

  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']
