name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: |
          cd backend
          mvn clean package -DskipTests

      - name: Copy jar to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.AWS_EC2_IP }}
          username: ${{ secrets.AWS_EC2_USER }}
          key: ${{ secrets.AWS_EC2_SSH_KEY }}
          source: "backend/target/demo-0.0.1-SNAPSHOT.jar"
          target: "/home/${{ secrets.AWS_EC2_USER }}/backend.jar"

      - name: Restart app on EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.AWS_EC2_IP }}
          username: ${{ secrets.AWS_EC2_USER }}
          key: ${{ secrets.AWS_EC2_SSH_KEY }}
          script: |
            # Check if java is installed, if not install it (example for Ubuntu/Debian)
            if ! command -v java > /dev/null; then
              echo "Java not found, installing..."
              sudo apt-get update
              sudo apt-get install -y openjdk-17-jdk
            else
              echo "Java is already installed"
            fi

            # Stop old app if running
            pkill -f 'java -jar backend.jar' || true
            
            # Start the new app in background
            nohup java -jar /home/${{ secrets.AWS_EC2_USER }}/backend.jar > /dev/null 2>&1 &

