name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: |
          cd backend
          mvn clean package -DskipTests

      - name: Move JAR to backend root folder
        run: |
          cd backend
          mv target/demo-0.0.1-SNAPSHOT.jar backend.jar

      - name: Copy jar to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.AWS_EC2_IP }}
          username: ${{ secrets.AWS_EC2_USER }}
          key: ${{ secrets.AWS_EC2_SSH_KEY }}
          source: "backend/backend.jar"
          target: "/home/${{ secrets.AWS_EC2_USER }}/backend.jar"
      
      - name: Restart app on EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.AWS_EC2_IP }}
          username: ${{ secrets.AWS_EC2_USER }}
          key: ${{ secrets.AWS_EC2_SSH_KEY }}
          script: |
            # Install Java 23 if not installed
            if ! java -version 2>&1 | grep '23'; then
              echo "Java 23 not found, installing..."
              wget https://github.com/adoptium/temurin23-binaries/releases/download/jdk-23.0.2+7/OpenJDK23U-jdk_x64_linux_hotspot_23.0.2_7.tar.gz -O /tmp/jdk23.tar.gz
              sudo mkdir -p /opt/jdk23
              sudo tar -xzf /tmp/jdk23.tar.gz -C /opt/jdk23 --strip-components=1
              sudo update-alternatives --install /usr/bin/java java /opt/jdk23/bin/java 1
              sudo update-alternatives --install /usr/bin/javac javac /opt/jdk23/bin/javac 1
              sudo update-alternatives --set java /opt/jdk23/bin/java
              sudo update-alternatives --set javac /opt/jdk23/bin/javac
              echo "Java 23 installed"
            else
              echo "Java 23 is already installed"
            fi

            java -jar /home/${{ secrets.AWS_EC2_USER }}/backend.jar/backend/backend.jar

